[package]
name = "minibpe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "minibpe"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
fancy-regex = "0.13.0"
